name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install dependencies
        run: |
          mvn install -DskipTests

      - name: Run Selenium Tests with Reporting
        run: |
          export DISPLAY=:99.0
          Xvfb :99 -screen 0 1280x1024x24 &
          mvn test -Dchrome.options="--headless --disable-gpu --no-sandbox --disable-dev-shm-usage --user-data-dir=/tmp/chrome-test-profile-${{ github.run_id }}"

      - name: Upload Test Report as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: selenium-test-report
          path: target/reports/extent-report*.html