name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      testType:
        description: 'Melyik teszteket futtassuk? (api, selenium, all)'
        required: true
        default: 'all'
      headlessMode:
        description: 'Futtassuk headless módban? (true/false)'
        required: true
        default: 'false'

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Google Chrome
        run: |
          sudo apt update
          sudo apt install -y wget curl unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt --fix-broken install -y

      - name: Install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests
        run: |
          mkdir -p ./chrome-user-data
          USER_DATA_DIR=$(pwd)/chrome-user-data
          echo "USER_DATA_DIR=$USER_DATA_DIR" >> $GITHUB_ENV

          if [ "${{ github.event.inputs.headlessMode }}" = "true" ]; then
            mvn test -DtestType=selenium -Dheadless=true -Duser-data-dir=$USER_DATA_DIR -X
          else
            mvn test -DtestType=selenium -Duser-data-dir=$USER_DATA_DIR -X
          fi

      - name: Check if tests passed
        run: |
          echo "### TEST RESULTS ###"
          tail -n 20 target/surefire-reports/*.log
          echo "### END TEST RESULTS ###"