name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Chrome
        run: |
          if [ "$CI" = "true" ]; then
            echo "CI környezet detektálva - Chrome letöltése"
            # Letöltjük a Chrome-ot és a ChromeDriver-t a CI környezetben
            curl -L -o ~/chrome/chrome-linux64.zip https://storage.googleapis.com/chrome-for-testing-public/140.0.7339.80/linux64/chrome-linux64.zip
            unzip ~/chrome/chrome-linux64.zip -d ~/chrome/
            echo "CHROME_BIN=~/chrome/chrome-linux64/chrome" >> $GITHUB_ENV
            curl -L -o ~/chrome/chromedriver-linux64.zip https://chromedriver.storage.googleapis.com/140.0.7339.80/chromedriver_linux64.zip
            unzip ~/chrome/chromedriver-linux64.zip -d ~/chrome/
            echo "webdriver.chrome.driver=~/chrome/chromedriver" >> $GITHUB_ENV
          else
            echo "Helyi fejlesztési környezet - Chrome már telepítve van"
            # Helyi környezetben nem kell letölteni - itt használja az alapértelmezett chrome-ot
            echo "CHROME_BIN=/usr/bin/google-chrome" >> $GITHUB_ENV
            echo "webdriver.chrome.driver=/usr/bin/chromedriver" >> $GITHUB_ENV
          fi

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install dependencies
        run: |
          mvn install -DskipTests

      - name: Run Selenium Tests
        run: |
          mvn test